import type { ProjectFile } from "./project-types";

export interface CursorConfig {
  projectName?: string;
  rules?: string[];
}

export interface CursorExportResult {
  success: boolean;
  zipUrl?: string;
  error?: string;
}

/**
 * Generate .cursorrules file for Cursor IDE
 */
export function generateCursorRules(
  files: ProjectFile[],
  projectName: string,
  customRules: string[] = []
): string {
  const detectedLanguages = [...new Set(files.map((f) => f.language))];
  
  const languageRules: Record<string, string> = {
    typescript: `
# TypeScript/React Rules
- Use TypeScript with strict mode
- Prefer interfaces over types for object shapes
- Use functional components with React hooks
- Use 'interface' instead of 'type' for component props
- Follow the existing code style in the project
`,
    python: `
# Python Rules
- Follow PEP 8 style guidelines
- Use type hints for function signatures
- Use list comprehensions where appropriate
- Prefer 'def' over lambda functions
`,
    rust: `
# Rust Rules
- Follow Rust idiomatic patterns
- Use Result<T, E> for error handling
- Prefer '?' operator over match for Result
- Use 'pub' for public APIs only
`,
  };

  let rulesContent = `# Cursor Rules for ${projectName}
# Generated by Mint AI

`;
  // Add language-specific rules
  detectedLanguages.forEach((lang) => {
    if (languageRules[lang] && !customRules.includes(languageRules[lang])) {
      rulesContent += languageRules[lang];
    }
  });

  // Add custom rules
  if (customRules.length > 0) {
    rulesContent += "\n# Custom Rules\n";
    customRules.forEach((rule) => {
      rulesContent += `${rule}\n`;
    });
  }

  return rulesContent;
}

/**
 * Generate cursor.json configuration
 */
export function generateCursorJson(
  projectName: string,
  files: ProjectFile[]
): Record<string, unknown> {
  const hasTsConfig = files.some((f) => f.path === "tsconfig.json");
  const hasJsConfig = files.some(
    (f) => f.path === "jsconfig.json" || f.path === ".eslintrc"
  );
  const hasPyProject = files.some((f) => f.path === "pyproject.toml");

  return {
    name: projectName,
    enableAutoIndex: true,
    enableCodeSuggestions: true,
    enableChat: true,
    enableTabAutocomplete: true,
    language: hasTsConfig
      ? "typescript"
      : hasPyProject
      ? "python"
      : hasJsConfig
      ? "javascript"
      : "plaintext",
    launcher: "cmd+k",
  };
}

/**
 * Export project for Cursor IDE
 * Returns a ZIP-compatible structure for Cursor
 */
export function exportForCursor(
  files: ProjectFile[],
  projectName: string,
  config: CursorConfig = {}
): { files: Array<{ path: string; content: string }>; success: boolean; error?: string } {
  try {
    const exportFiles: Array<{ path: string; content: string }> = [];

    // Add all project files
    files.forEach((file) => {
      exportFiles.push({
        path: file.path,
        content: file.content,
      });
    });

    // Add .cursor/rules if custom rules exist
    const rules = generateCursorRules(files, projectName, config.rules || []);
    exportFiles.push({
      path: ".cursor/rules.mdc",
      content: rules,
    });

    // Add cursor.json
    const cursorJson = generateCursorJson(projectName, files);
    exportFiles.push({
      path: ".cursor/settings.json",
      content: JSON.stringify(cursorJson, null, 2),
    });

    return {
      files: exportFiles,
      success: true,
    };
  } catch (error) {
    console.error("Cursor export error:", error);
    return {
      files: [],
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

/**
 * Generate .gitignore for the project
 */
export function generateCursorGitignore(files: ProjectFile[]): string {
  const ignorePatterns = [
    "# Cursor",
    ".cursor/",
    "",
    "# Dependencies",
    "node_modules/",
    "",
    "# Build output",
    "dist/",
    "build/",
    ".next/",
    "",
    "# Environment",
    ".env",
    ".env.local",
    ".env.*.local",
    "",
    "# IDE",
    ".vscode/",
    ".idea/",
    "*.swp",
    "*.swo",
    "*~",
    "",
    "# OS",
    ".DS_Store",
    "Thumbs.db",
    "",
    "# Logs",
    "*.log",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "",
  ];

  // Add language-specific ignores
  const languages = new Set(files.map((f) => f.language));
  
  if (languages.has("python")) {
    ignorePatterns.push("", "# Python", "__pycache__/", "*.pyc", "*.pyo", "*.pyd", ".Python", "venv/", "env/");
  }

  if (languages.has("rust")) {
    ignorePatterns.push("", "# Rust", "target/", "Cargo.lock");
  }

  if (languages.has("go")) {
    ignorePatterns.push("", "# Go", "*.exe", "*.exe~", "*.dll", "*.so", "*.dylib", "vendor/");
  }

  return ignorePatterns.join("\n");
}

/**
 * Generate README for Cursor project
 */
export function generateCursorReadme(
  projectName: string,
  files: ProjectFile[]
): string {
  const detectedLanguages = [...new Set(files.map((f) => f.language))];
  
  return `# ${projectName}

Generated with [Mint AI](https://mint-ai.app) for Cursor IDE

## Opened with Cursor

This project is optimized for development in [Cursor](https://cursor.sh).

## Quick Start

${
  detectedLanguages.includes("typescript") || detectedLanguages.includes("tsx")
    ? "```bash\nnpm install\nnpm run dev\n```"
    : detectedLanguages.includes("python")
    ? "```bash\npip install -r requirements.txt\npython main.py\n```"
    : detectedLanguages.includes("rust")
    ? "```bash\ncargo run\n```"
    : "See file-specific instructions below."
}

## Files

${files.map((f) => `- \`${f.path}\``).join("\n")}

## Cursor Features

This project includes:
- **.cursor/rules.mdc** - Custom rules for AI assistance
- **.cursor/settings.json** - Project-specific settings

## Additional Setup

${
  files.some((f) => f.language === "typescript" || f.language === "tsx")
    ? "- Install dependencies: `npm install`\n- Configure TypeScript in `tsconfig.json`"
    : files.some((f) => f.language === "python")
    ? "- Create virtual environment: `python -m venv venv`\n- Install dependencies: `pip install -r requirements.txt`"
    : "- Follow instructions in individual files"
}

## License

MIT
`;
}
